remote_theme: jekyll/minima
title: Sacra - Notícias
description: Anúncios e novidades sobre o app

permalink: pretty
lang: pt-BR
date_format: "%d de %B de %Y"

minima:
  skin: classic
  show_excerpts: true

